### PR TITLE
feat: configure extra containers for Deployment

### PR DESCRIPTION
**Pull request by mitchnielsen**
Adds a new field to the PrefectServer spec where you can pass a list of extra containers to the Prefect Server Deployment.

Related to https://linear.app/prefect/document/auth-design-doc-7b1ae89e5382

CLOSES CLOUD-422

### CODE REVIEW

**Review by jakekaplan — APPROVED** [review]
Looks great to my untrained eyes!

**Review by chrisguidry — APPROVED** [review]
Looks awesome, what do you think about adding it to `PrefectWorkPool` for completeness?

**Comment by mitchnielsen** [comment]
> what do you think about adding it to PrefectWorkPool for completeness?

Sure thing, I wasn't sure if there was a use case there so happy to add it 👍🏼

**Comment by mitchnielsen** [comment]
Added to WorkPools in ade9ba6.

**Comment by chrisguidry** [comment]
Yeah no use case that I can think of just yet, just want to keep the affordances for both of them the same as much as possible

**Pull request merged**
